### Nyelv mappa JSON fájl olvasása
GET http://127.0.0.1:3000/api/nyelv_alapjan_JSON_olvasas/hungarian/main_menu.json

### Regisztráció
POST http://127.0.0.1:3000/api/register
Content-Type: application/json
{
    
}

### Bejelentkezés
POST http://127.0.0.1:3000/api/register
Content-Type: application/json
{
    
}

### Felhasználói achivement adatok lekérése
GET http://127.0.0.1:3000/api/showachivements/4/hungarian

### Felhasználói adott mentés adatok lekérése
GET http://127.0.0.1:3000/api/mentesmeghiv/7/3